dist: xenial
os: linux
sudo: required
language: cpp
compiler:
  - gcc
  - clang
install:
  - pushd depends
  - make
script:
  - ./autogen.sh 
  - ./configure --prefix=$PWD/depends/x86_64-pc-linux-gnu
  - make src/bitcoind -j4
  - make src/bitcoin-cli -j4
after_script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT_LOG